imports:
    - { resource: config.yml }
    - { resource: parameters_production.php }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# doctrine:
#     dbal:
#         driver:   "pdo_pgsql"
#         host:     "ec2-54-197-238-19.compute-1.amazonaws.com"
#         port:     "5432"
#         dbname:   "dap1lfh1gcsa"
#         user:     "bbpajyqvifrdct"
#         password: "h2VgLyTjg1U5BoyLem8QCEZTUW"
#         charset:  UTF8

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
#            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            path: "php://stderr"
            level: debug
