security:
    encoders:
        Acme\boletinesBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12
    providers:
        our_db_provider:
            entity:
                class: BoletinesBundle:Usuario
                property: nombre

    firewalls:
        defualt:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: login_redirect
            logout:
                path: /logout
                target: /login/login

    access_control:
        - { path: ^/institucion, roles: ROLE_ADMIN }
