#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
#
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                        login_path:  login
#                        check_path:  login_check
#            logout:
#                path:   _demo_logout
#                target: _demo
#        default:
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
#
#    access_control:
##        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#         - { path: ^/admin, roles: ROLE_ADMIN }
#        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


# app/config/security.yml
#security:
#    firewalls:
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
#
#    access_control:
#        - { path: ^/, roles: ROLE_ADMIN }
#
#    providers:
#        in_memory:
#            memory:
#                users:
#                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
#
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
    providers:
        administrators:
            entity: { class: BoletinesBundle:Usuario, property: nombreUsuario }
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
#        in_memory:
#            memory:
#                users:
#                    fede:  { password: casta, roles: 'ROLE_USER' }
#                    facu: { password: clarat, roles: 'ROLE_ADMIN' }
#                    nahui: { password: lattessi, roles: 'ROLE_ADMIN' }
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Acme\boletinesBundle\Entity\Usuario:
            algorithm:        plaintext
            encode_as_base64: false
            iterations:       1

    access_control:
        - { path: ^/institucion, roles: ROLE_ADMIN }