asistencia:
    path:     /
    defaults: { _controller: BoletinesBundle:Asistencia:index }

asistencia_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Asistencia:new }

asistencia_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Asistencia:delete }

asistencia_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Asistencia:getOne }

asistencia_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Asistencia:edit }