boletin:
    path:     /
    defaults: { _controller: BoletinesBundle:Boletin:index }

boletin_cargar_nota:
    path:     /cargar_nota/{materiaId}/{periodoId}
    defaults: { _controller: BoletinesBundle:Boletin:cargarNota }

boletin_index_directivo:
    path:     /directivo
    defaults: { _controller: BoletinesBundle:Boletin:indexDirectivo }

boletin_validar_notas:
    path:     /validar_notas/{materiaId}
    defaults: { _controller: BoletinesBundle:Boletin:validarNota }

boletin_show:
    path:     /show
    defaults: { _controller: BoletinesBundle:Boletin:show }
