boletin:
    path:     /
    defaults: { _controller: BoletinesBundle:Boletin:index }

boletin_cargar_nota:
    path:     /cargar_nota/{materiaId}/{periodoId}
    defaults: { _controller: BoletinesBundle:Boletin:cargarNota }
