convivencia:
    path:     /
    defaults: { _controller: BoletinesBundle:Convivencia:index }

convivencia_autocompletar:
    path:     /autocompletar
    defaults: { _controller: BoletinesBundle:Alumno:autocompletar }

convivencia_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Convivencia:new }

convivencia_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Convivencia:delete }

convivencia_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Convivencia:getOne }

convivencia_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Convivencia:edit }