establecimiento:
    path:     /
    defaults: { _controller: BoletinesBundle:Establecimiento:index }

establecimiento_new_with_institucion:
    path:    /{institucionId}/new
    defaults: { _controller: BoletinesBundle:Establecimiento:newWithInstitucion }

establecimiento_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:delete }

establecimiento_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:getOne }

establecimiento_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:edit }
