establecimiento:
    path:     /
    defaults: { _controller: BoletinesBundle:Establecimiento:index }

establecimiento_new_with_institucion:
    path:    /{institucionId}/new
    defaults: { _controller: BoletinesBundle:Establecimiento:newWithInstitucion }

establecimiento_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:delete }

establecimiento_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:getOne }

establecimiento_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:edit }

establecimiento_edit_director:
    path:     /director/edit
    defaults: { _controller: BoletinesBundle:Establecimiento:editDirecotor}

establecimiento_add_especialidad:
    path:     /{id}/add_especialidad
    defaults: { _controller: BoletinesBundle:Establecimiento:addEspecialidad }

establecimiento_remove_especialidad:
    path:     /remove_especialidad/{id}
    defaults: { _controller: BoletinesBundle:Establecimiento:removeEspecialidad }

establecimiento_show_especialidades:
    path:     /{id}/especialidades
    defaults: { _controller: BoletinesBundle:Establecimiento:showEspecialidades }
