evaluacion:
    path:     /
    defaults: { _controller: BoletinesBundle:Evaluacion:index }

evaluacion_new:
    path:    /new/{id}
    defaults: { _controller: BoletinesBundle:Evaluacion:new }

evaluacion_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Evaluacion:delete }

evaluacion_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Evaluacion:getOne }

evaluacion_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Evaluacion:edit }

evaluacion_calificar:
    path:     /calificar/{id}
    defaults: { _controller: BoletinesBundle:Evaluacion:calificar }