examen:
    path:     /
    defaults: { _controller: BoletinesBundle:Examen:index }

examen_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Examen:new }

examen_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Examen:delete }

examen_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Examen:getOne }

examen_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Examen:edit }