grupoAlumno:
    path:     /
    defaults: { _controller: BoletinesBundle:GrupoAlumno:index }

grupoAlumno_autocompletar:
    path:     /autocompletar
    defaults: { _controller: BoletinesBundle:Alumno:autocompletar }

grupoAlumno_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:GrupoAlumno:new }

grupoAlumno_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:GrupoAlumno:delete }

grupoAlumno_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:GrupoAlumno:getOne }

grupoAlumno_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:GrupoAlumno:edit }