grupoUsuario:
    path:     /
    defaults: { _controller: BoletinesBundle:GrupoUsuario:index }

grupoUsuario_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:GrupoUsuario:new }

grupoUsuario_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:GrupoUsuario:delete }

grupoUsuario_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:GrupoUsuario:getOne }

grupoUsuario_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:GrupoUsuario:edit }