historic_on:
    path:     /on
    defaults: { _controller: BoletinesBundle:Historic:on }

historic_off:
    path:     /off
    defaults: { _controller: BoletinesBundle:Historic:off }


historic_up:
    path:     /up
    defaults: { _controller: BoletinesBundle:Historic:upYear }


historic_down:
    path:     /down
    defaults: { _controller: BoletinesBundle:Historic:downYear }
