institucion_search:
    path:     /search
    defaults: { _controller: BoletinesBundle:Institucion:search }

institucion:
    path:     /
    defaults: { _controller: BoletinesBundle:Institucion:index }

institucion_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Institucion:new }

institucion_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Institucion:delete }

institucion_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Institucion:getOne }

institucion_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Institucion:edit }

institucion_ver_alumnos:
    path:     /{id}/alumnos
    defaults: { _controller: BoletinesBundle:Institucion:getalumnos }

institucion_agregar_establecimiento:
    path:     /agregar/{id}
    defaults: { _controller: BoletinesBundle:Institucion:agregarEstablecimiento }
