institucion:
    path:     /
    defaults: { _controller: BoletinesBundle:Institucion:index }

institucion_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Institucion:new }

institucion_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Institucion:delete }

institucion_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Institucion:getOne }

institucion_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Institucion:edit }