justificacion:
    path:     /
    defaults: { _controller: BoletinesBundle:Justificacion:index }

justificacion_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Justificacion:new }

justificacion_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Justificacion:delete }

justificacion_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Justificacion:getOne }

justificacion_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Justificacion:edit }