login:
    pattern:   /login
    defaults:  { _controller: BoletinesBundle:Login:login }

login_check:
    pattern:   /login_check

login_redirect:
    pattern:   /login/redirect
    defaults:  { _controller: BoletinesBundle:Login:redirect }

