mensaje:
    path:     /
    defaults: { _controller: BoletinesBundle:Mensaje:index }

mensaje_autocompletar:
    path:     /autocompletar
    defaults: { _controller: BoletinesBundle:Mensaje:autocompletar }

mensaje_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Mensaje:new }

mensaje_save_borrador:
    path:    /saveBorrador
    defaults: { _controller: BoletinesBundle:Mensaje:saveBorrador }

mensaje_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:delete }

mensaje_delete_checked:
    path:     /deleteCheckedMensajes
    defaults: { _controller: BoletinesBundle:Mensaje:deleteCheckedMensajes }

mensaje_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOne }

mensaje_enviado_autocompletar:
    path:     /enviado/autocompletar
    defaults: { _controller: BoletinesBundle:Mensaje:autocompletar }

mensaje_enviado_show:
    path:     /enviado/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOneEnviado }

mensaje_borrado_autocompletar:
    path:     /borrado/autocompletar
    defaults: { _controller: BoletinesBundle:Mensaje:autocompletar }

mensaje_borrado_show:
    path:     /borrado/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOneBorrado }

mensaje_borrador_autocompletar:
    path:     /borrador/autocompletar
    defaults: { _controller: BoletinesBundle:Mensaje:autocompletar }

mensaje_borrador_show:
    path:     /borrador/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOneBorrador }
