mensaje:
    path:     /
    defaults: { _controller: BoletinesBundle:Mensaje:index }

mensaje_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Mensaje:new }

mensaje_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:delete }

mensaje_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOne }

mensaje_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:edit }