mensaje:
    path:     /
    defaults: { _controller: BoletinesBundle:Mensaje:index }

mensaje_autocompletar:
    path:     /autocompletar
    defaults: { _controller: BoletinesBundle:Mensaje:autocompletar }

mensaje_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Mensaje:new }

mensaje_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:delete }

mensaje_delete_checked:
    path:     /deleteCheckedMensajes
    defaults: { _controller: BoletinesBundle:Mensaje:deleteCheckedMensajes }

mensaje_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOne }

mensaje_enviado_show:
    path:     /enviado/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOneEnviado }

mensaje_borrado_show:
    path:     /borrado/{id}
    defaults: { _controller: BoletinesBundle:Mensaje:getOneBorrado }
