notificacion:
    path:     /
    defaults: { _controller: BoletinesBundle:Notificacion:index }

notificacion_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Notificacion:new }

notificacion_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Notificacion:delete }

notificacion_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Notificacion:getOne }

notificacion_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Notificacion:edit }