#padre_add_from_director:
#    path:     /agregar
#    defaults: { _controller: BoletinesBundle:Padre:addFromDirector }

padre_delete_from_director:
    path:     /director/delete/{id}
    defaults: { _controller: BoletinesBundle:Padre:deleteDirector }
    
padre:
    path:     /
    defaults: { _controller: BoletinesBundle:Padre:index }

padre_autocompletar:
    path:     /autocompletar
    defaults: { _controller: BoletinesBundle:Alumno:autocompletar }

padre_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Padre:new }

padre_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Padre:delete }

padre_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Padre:getOne }

padre_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Padre:edit }
