periodo:
    path:     /
    defaults: { _controller: BoletinesBundle:Periodo:index }

periodo_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Periodo:new }

periodo_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Periodo:delete }

periodo_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Periodo:getOne }

periodo_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Periodo:edit }
