reporte:
    path:     /
    defaults: { _controller: BoletinesBundle:Reporte:new }
reporte_new:
    path:     /new
    defaults: { _controller: BoletinesBundle:Reporte:new }
reporte_ajax:
    path:     /ajaxreporte
    defaults: { _controller: BoletinesBundle:Reporte:busquedaAjax }