tipoMateria:
    path:     /
    defaults: { _controller: BoletinesBundle:TipoMateria:index }

tipoMateria_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:TipoMateria:new }

tipoMateria_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:TipoMateria:delete }

tipoMateria_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:TipoMateria:getOne }

tipoMateria_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:TipoMateria:edit }