usuario_email_recovery_password:
    path:     /recoverpassword/
    defaults: { _controller: BoletinesBundle:Usuario:emailRecoveryPassword }

usuario_send_email_recovery_password:
    path:     /sendrecoverpassword/
    defaults: { _controller: BoletinesBundle:Usuario:sendEmailRecoveryPassword }

usuario_reset_password:
    path:     /resetpassword/{token}
    defaults: { _controller: BoletinesBundle:Usuario:resetPassword }

usuario_do_reset_password:
    path:     /resetpassword/
    defaults: { _controller: BoletinesBundle:Usuario:doResetPassword }

usuario:
    path:     /
    defaults: { _controller: BoletinesBundle:Usuario:index }

usuario_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Usuario:new }

usuario_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Usuario:delete }

usuario_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Usuario:edit }

usuario_index_admin:
    path:     /indexPorInstitucion/
    defaults: { _controller: BoletinesBundle:Usuario:indexConInstitucion }

usuario_edit_institucion:
    path:     /{institucionId}/edit
    defaults: { _controller: BoletinesBundle:Usuario:editConInstitucion }

usuario_new_institucion:
    path:     /{institucionId}/new
    defaults: { _controller: BoletinesBundle:Usuario:newConInstitucion }

usuario_edit2:
    path:     /edit2/
    defaults: { _controller: BoletinesBundle:Usuario:edit2 }

usuario_new2:
    path:     /new2/
    defaults: { _controller: BoletinesBundle:Usuario:new2 }

usuario_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Usuario:getOne }
