usuario:
    path:     /
    defaults: { _controller: BoletinesBundle:Usuario:index }

usuario_new:
    path:    /new
    defaults: { _controller: BoletinesBundle:Usuario:new }

usuario_delete:
    path:     /delete/{id}
    defaults: { _controller: BoletinesBundle:Usuario:delete }

usuario_show:
    path:     /{id}
    defaults: { _controller: BoletinesBundle:Usuario:getOne }

usuario_edit:
    path:     /edit/{id}
    defaults: { _controller: BoletinesBundle:Usuario:edit }