Acme\boletinesBundle\Entity\Actividad:
    type: entity
    table: actividad
    indexes:
        FK_usuario:
            columns:
                - usuario_carga_id
        FK_archivo_id:
            columns:
                - archivo_id
        FK_institucion_id:
            columns:
                - institucion_id
        FK_establecimiento_id:
            columns:
                - establecimiento_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        descripcion:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        fechaHoraInicio:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_hora_inicio
        fechaHoraFin:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_hora_fin
        creationTime:
            type: datetime
            nullable: false
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: false
            comment: ''
            column: update_time
    manyToOne:
        usuarioCarga:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_carga_id:
                    referencedColumnName: id
            orphanRemoval: false
        archivo:
            targetEntity: Archivo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                archivo_id:
                    referencedColumnName: id
            orphanRemoval: false
        institucion:
            targetEntity: Institucion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                institucion_id:
                    referencedColumnName: id
            orphanRemoval: false
        establecimiento:
            targetEntity: Establecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                establecimiento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
