Acme\boletinesBundle\Entity\AlumnoAsistencia:
    type: entity
    table: alumno_asistencia
    indexes:
        FK_D30A8664320260C0:
            columns:
                - alumno_id
        FK_D30A866455D9EBE2:
            columns:
                - justificacion_id
        FK_D30A86647DACCA5A:
            columns:
                - asistencia_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valor:
            type: string
            nullable: false
            length: 1
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        alumno:
            targetEntity: Alumno
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                alumno_id:
                    referencedColumnName: id
            orphanRemoval: false
        justificacion:
            targetEntity: Justificacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                justificacion_id:
                    referencedColumnName: id
            orphanRemoval: false
        asistencia:
            targetEntity: Asistencia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                asistencia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
