Acme\boletinesBundle\Entity\Archivo:
    type: entity
    table: archivo
    indexes:
        FK_3529B4827FA0C10D:
            columns:
                - usuario_carga_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreParaMostrar:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nombre_para_mostrar
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        rutaArchivo:
            type: string
            nullable: false
            length: 75
            fixed: false
            comment: ''
            column: ruta_archivo
        fechaSubida:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_subida
        fechaActualizacion:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_actualizacion
    manyToOne:
        usuarioCarga:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_carga_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
