Acme\boletinesBundle\Entity\Avatar:
    type: entity
    table: avatar
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        path:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
