Acme\boletinesBundle\Entity\Calificacion:
    type: entity
    table: calificacion
    indexes:
        FK_8A3AF218320260C0:
            columns:
                - alumno_id
        fk_calificacion_evaluacion:
            columns:
                - evaluacion_id
        fk_usuario_calificacion_idx:
            columns:
                - usuario_carga_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: datetime
            nullable: true
            comment: ''
        valor:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        comentario:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        validada:
            type: boolean
            nullable: false
            comment: ''
        fechaCreacion:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_creacion
        fechaActualizacion:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_actualizacion
    manyToOne:
        alumno:
            targetEntity: Alumno
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                alumno_id:
                    referencedColumnName: id
            orphanRemoval: false
        evaluacion:
            targetEntity: Evaluacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                evaluacion_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuarioCarga:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_carga_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
