Acme\boletinesBundle\Entity\Ciudad:
    type: entity
    table: ciudad
    indexes:
        FK_provincida_id:
            columns:
                - provincia_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        provincia:
            targetEntity: Provincia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                provincia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
