Acme\boletinesBundle\Entity\DocenteMateria:
    type: entity
    table: docente_materia
    indexes:
        FK_517E8597230266D4:
            columns:
                - docente_id
        FK_517E8597B36DFBF4:
            columns:
                - materia_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        docente:
            targetEntity: Docente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                docente_id:
                    referencedColumnName: id
            orphanRemoval: false
        materia:
            targetEntity: Materia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                materia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
