Acme\boletinesBundle\Entity\Docente:
    type: entity
    table: docente
    indexes:
        FK_FD9FCFA4FCF8192D:
            columns:
                - usuario_id
        fk_ciudad_docente:
            columns:
                - ciudad_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
        apellido:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
        dni:
            type: string
            nullable: true
            length: 8
            fixed: false
            comment: ''
        direccion:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        codigoPostal:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: codigo_postal
        codigoPais:
            type: string
            nullable: true
            length: 4
            fixed: false
            comment: ''
            column: codigo_pais
        codigoArea:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
            column: codigo_area
        telefono:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
        titulo:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        fechaIngreso:
            type: date
            nullable: true
            comment: ''
            column: fecha_ingreso
        fechaNacimiento:
            type: date
            nullable: true
            comment: ''
            column: fecha_nacimiento
        foto:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        esTitular:
            type: boolean
            nullable: true
            comment: ''
            column: es_titular
        observaciones:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        establecimientoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: establecimiento_id
        creationTime:
            type: datetime
            nullable: false
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: false
            comment: ''
            column: update_time
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        ciudad:
            targetEntity: Ciudad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciudad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
