Acme\boletinesBundle\Entity\Especialidad:
    type: entity
    table: especialidad
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        descripcion:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    lifecycleCallbacks: {  }
