Acme\boletinesBundle\Entity\Establecimiento:
    type: entity
    table: establecimiento
    indexes:
        FK_94A4D17EEF433A34:
            columns:
                - institucion_id
        fk_ciudad_establecimiento:
            columns:
                - ciudad_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        direccion:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        codigoPostal:
            type: string
            nullable: true
            length: 12
            fixed: false
            comment: ''
            column: codigo_postal
        longitud:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        latitud:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        fechaInauguracion:
            type: date
            nullable: true
            comment: ''
            column: fecha_inauguracion
        codigoPais:
            type: string
            nullable: true
            length: 4
            fixed: false
            comment: ''
            column: codigo_pais
        codigoArea:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
            column: codigo_area
        telefono:
            type: string
            nullable: true
            length: 12
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        observaciones:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        institucion:
            targetEntity: Institucion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                institucion_id:
                    referencedColumnName: id
            orphanRemoval: false
        ciudad:
            targetEntity: Ciudad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciudad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
