Acme\boletinesBundle\Entity\GrupoAlumno:
    type: entity
    table: grupo_alumno
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        esCurso:
            type: boolean
            nullable: false
            comment: ''
            column: es_curso
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    lifecycleCallbacks: {  }
