Acme\boletinesBundle\Entity\Institucion:
    type: entity
    table: institucion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        logo:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        cuit:
            type: string
            nullable: true
            length: 11
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    lifecycleCallbacks: {  }
