Acme\boletinesBundle\Entity\Justificacion:
    type: entity
    table: justificacion
    indexes:
        FK_EBF13A877FA0C10D:
            columns:
                - usuario_carga_id
        FK_EBF13A87EBB41DF2:
            columns:
                - archivo_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        comentario:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        fechaCarga:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_carga
        fechaModificacion:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_modificacion
    manyToOne:
        usuarioCarga:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_carga_id:
                    referencedColumnName: id
            orphanRemoval: false
        archivo:
            targetEntity: Archivo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                archivo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
