Acme\boletinesBundle\Entity\MateriaArchivo:
    type: entity
    table: materia_archivo
    indexes:
        FK_566A8CA4B36DFBF4:
            columns:
                - materia_id
        FK_566A8CA4EBB41DF2:
            columns:
                - archivo_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        materia:
            targetEntity: Materia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                materia_id:
                    referencedColumnName: id
            orphanRemoval: false
        archivo:
            targetEntity: Archivo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                archivo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
