Acme\boletinesBundle\Entity\Materia:
    type: entity
    table: materia
    indexes:
        FK_6DF052845DC80656:
            columns:
                - tipo_materia_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        tipoMateria:
            targetEntity: TipoMateria
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_materia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
