Acme\boletinesBundle\Entity\Notificacion:
    type: entity
    table: notificacion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        texto:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
        fechaEnvio:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_envio
        url:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
