Acme\boletinesBundle\Entity\NotificacionUsuario:
    type: entity
    table: notificacion_usuario
    indexes:
        fk_not_usuario_idx:
            columns:
                - notificacion_id
        fk_usuario_not_idx:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        notificado:
            type: boolean
            nullable: true
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        notificacion:
            targetEntity: Notificacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                notificacion_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
