Acme\boletinesBundle\Entity\Provincia:
    type: entity
    table: provincia
    indexes:
        fk_pais_provincia_idx:
            columns:
                - pais_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        pais:
            targetEntity: Pais
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pais_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
