Acme\boletinesBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
        descripcion:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks: {  }
