Acme\boletinesBundle\Entity\Token:
    type: entity
    table: token
    indexes:
        fk_usuario_token_idx:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        token:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        expirationTime:
            type: datetime
            nullable: false
            comment: ''
            column: expiration_time
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
