Acme\boletinesBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        FK_2265B05D90F1D76D:
            columns:
                - rol_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        idEntidadAsociada:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_entidad_asociada
        email:
            type: string
            nullable: true
            length: 65
            fixed: false
            comment: ''
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        rol:
            targetEntity: Rol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
