Acme\boletinesBundle\Entity\UsuarioGrupoUsuario:
    type: entity
    table: usuario_grupo_usuario
    indexes:
        IDX_8BDF2024FCF8192D:
            columns:
                - usuario_id
        IDX_8BDF2024C344EF9F:
            columns:
                - grupo_usuario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        creationTime:
            type: datetime
            nullable: true
            comment: ''
            column: creation_time
        updateTime:
            type: datetime
            nullable: true
            comment: ''
            column: update_time
    manyToOne:
        grupoUsuario:
            targetEntity: GrupoUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                grupo_usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
