boletines_materia:
    resource: "@BoletinesBundle/Resources/config/routing/materia.yml"
    prefix:   /materia

boletines_institucion:
    resource: "@BoletinesBundle/Resources/config/routing/institucion.yml"
    prefix:   /institucion

boletines_tipoMaeria:
    resource: "@BoletinesBundle/Resources/config/routing/tipoMateria.yml"
    prefix:   /tipomateria



