boletines_materia:
    resource: "@BoletinesBundle/Resources/config/routing/materia.yml"
    prefix:   /materia

boletines_materia:
    resource: "@BoletinesBundle/Resources/config/routing/institucion.yml"
    prefix:   /institucion


