boletines_materia:
    resource: "@BoletinesBundle/Resources/config/routing/materia.yml"
    prefix:   /materia

boletines_institucion:
    resource: "@BoletinesBundle/Resources/config/routing/institucion.yml"
    prefix:   /institucion

boletines_establecimiento:
    resource: "@BoletinesBundle/Resources/config/routing/establecimiento.yml"
    prefix:   /establecimiento

boletines_tipoMateria:
    resource: "@BoletinesBundle/Resources/config/routing/tipoMateria.yml"
    prefix:   /tipomateria

boletines_docente:
    resource: "@BoletinesBundle/Resources/config/routing/docente.yml"
    prefix:   /docente

boletines_director:
    resource: "@BoletinesBundle/Resources/config/routing/director.yml"
    prefix:   /director

boletines_actividad:
    resource: "@BoletinesBundle/Resources/config/routing/actividad.yml"
    prefix:   /actividad

boletines_usuario:
    resource: "@BoletinesBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario

boletines_examen:
    resource: "@BoletinesBundle/Resources/config/routing/examen.yml"
    prefix:   /examen

boletines_alumno:
    resource: "@BoletinesBundle/Resources/config/routing/alumno.yml"
    prefix:   /alumno

boletines_calificacion:
    resource: "@BoletinesBundle/Resources/config/routing/calificacion.yml"
    prefix:   /calificacion

boletines_convivencia:
    resource: "@BoletinesBundle/Resources/config/routing/convivencia.yml"
    prefix:   /convivencia

boletines_asistencia:
    resource: "@BoletinesBundle/Resources/config/routing/asistencia.yml"
    prefix:   /asistencia

boletines_grupoAlumno:
    resource: "@BoletinesBundle/Resources/config/routing/grupoAlumno.yml"
    prefix:   /grupoAlumno

boletines_grupoUsuario:
    resource: "@BoletinesBundle/Resources/config/routing/grupoUsuario.yml"
    prefix:   /grupoUsuario

boletines_justificacion:
    resource: "@BoletinesBundle/Resources/config/routing/justificacion.yml"
    prefix:   /justificacion

boletines_mensaje:
    resource: "@BoletinesBundle/Resources/config/routing/mensaje.yml"
    prefix:   /mensaje

boletines_notificacion:
    resource: "@BoletinesBundle/Resources/config/routing/notificacion.yml"
    prefix:   /notificacion

boletines_calendario:
    resource: "@BoletinesBundle/Resources/config/routing/calendario.yml"
    prefix:   /calendario

boletines_login:
    resource: "@BoletinesBundle/Resources/config/routing/login.yml"
    prefix:   /login

boletines_home:
    resource: "@BoletinesBundle/Resources/config/routing/home.yml"
    prefix:   /home

logout:
    path:   /logout

login_index:
    pattern:   /
    defaults:  { _controller: BoletinesBundle:Login:login }

cambiar_hijo:
    pattern:  /home/{id}
    defaults: { _controller: BoletinesBundle:Login:cambiarHijo }

antibullyng:
    pattern:  /antibullyng/{id}
    defaults: { _controller: BoletinesBundle:Alumno:antybullyng }
