boletines_materia:
    resource: "@BoletinesBundle/Resources/config/routing/materia.yml"
    prefix:   /materia

boletines_institucion:
    resource: "@BoletinesBundle/Resources/config/routing/institucion.yml"
    prefix:   /institucion

boletines_establecimiento:
    resource: "@BoletinesBundle/Resources/config/routing/establecimiento.yml"
    prefix:   /establecimiento

boletines_tipoMateria:
    resource: "@BoletinesBundle/Resources/config/routing/tipoMateria.yml"
    prefix:   /tipomateria

boletines_docente:
    resource: "@BoletinesBundle/Resources/config/routing/docente.yml"
    prefix:   /docente

boletines_actividad:
    resource: "@BoletinesBundle/Resources/config/routing/actividad.yml"
    prefix:   /actividad

