services:
#    boletines.example:
#        class: Acme\boletinesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      boletines.servicios.actividad:
          class: Acme\boletinesBundle\Servicios\ActividadService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.sesion:
          class: Acme\boletinesBundle\Servicios\SesionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
