services:
#    boletines.example:
#        class: Acme\boletinesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      boletines.servicios.actividad:
          class: Acme\boletinesBundle\Servicios\ActividadService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.sesion:
          class: Acme\boletinesBundle\Servicios\SesionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.notificacion:
          class: Acme\boletinesBundle\Servicios\NotificacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.mensaje:
          class: Acme\boletinesBundle\Servicios\MensajeService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.creacion:
          class: Acme\boletinesBundle\Servicios\CreacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.muchosamuchos:
          class: Acme\boletinesBundle\Servicios\MuchosAmuchosService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.asistencia:
          class: Acme\boletinesBundle\Servicios\AsistenciaService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.calificacion:
          class: Acme\boletinesBundle\Servicios\CalificacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.convivencia:
          class: Acme\boletinesBundle\Servicios\ConvivenciaService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.padre:
          class: Acme\boletinesBundle\Servicios\PadreService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.grupoAlumno:
          class: Acme\boletinesBundle\Servicios\GrupoAlumnoService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.grupoUsuario:
          class: Acme\boletinesBundle\Servicios\GrupoUsuarioService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.materia:
          class: Acme\boletinesBundle\Servicios\MateriaService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.evaluacion:
          class: Acme\boletinesBundle\Servicios\EvaluacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      twig.extension.intl:
          class: Twig_Extensions_Extension_Intl
          tags:
              - { name: twig.extension }
      boletines.listener.usurio.postLoad:
          class: Acme\boletinesBundle\EventListener\UsuarioPostLoadListener
          tags:
              - { name: doctrine.event_listener, event: postLoad }
      boletines.servicios.archivo:
          class: Acme\boletinesBundle\Servicios\ArchivoService
          arguments:
              filesystem: @archivos_filesystem
              entityManager: @doctrine.orm.entity_manager
