services:
#    boletines.example:
#        class: Acme\boletinesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      boletines.servicios.actividad:
          class: Acme\boletinesBundle\Servicios\ActividadService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.sesion:
          class: Acme\boletinesBundle\Servicios\SesionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.notificacion:
          class: Acme\boletinesBundle\Servicios\NotificacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.creacion:
          class: Acme\boletinesBundle\Servicios\CreacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.muchosamuchos:
          class: Acme\boletinesBundle\Servicios\MuchosAmuchosService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.asistencia:
          class: Acme\boletinesBundle\Servicios\AsistenciaService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.calificacion:
          class: Acme\boletinesBundle\Servicios\CalificacionService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      boletines.servicios.convivencia:
          class: Acme\boletinesBundle\Servicios\ConvivenciaService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      twig.extension.intl:
          class: Twig_Extensions_Extension_Intl
          tags:
              - { name: twig.extension }
